export const QUESTION_BANK: string[] = [
  "What is a surprising fact about {hotSeat} that most people don't know?",
  "If {hotSeat} had to eat one meal for the rest of their life, what would it be?",
  "What is {hotSeatPossessive} most irrational fear?",
  "If {hotSeat} could instantly learn any skill, what would it be?",
  "Which fictional character does {hotSeat} relate to the most?",
  "What is a guilty pleasure song {hotSeat} knows by heart?",
  "Where would {hotSeat} travel if money and time were no issue?",
  "What is the best prank {hotSeat} has ever pulled off?",
  "If {hotSeat} could swap lives with someone for a day, who would it be?",
  "If {hotSeat} had to describe {randomPlayer} in one word, what would it be?",
  "What type of contest would {hotSeat} win between all the people in the room?",
  "If {hotSeat} were homeless, what would {hotSeat} write on their sign to get spare change?",
  "{hotSeat} is on the front page of next Sunday's local paper — what's the headline?",
  "What is the most embarrassing thing {hotSeat} has ever Googled?",
  "What job would {hotSeat} be absolutely horrible at?",
  "If {hotSeat} purchased their own island, what would they name it?",
  "What is the first thing {hotSeat} would do if they won the lottery?",
  "What is the smallest thing {hotSeat} is grateful for?",
  "If {hotSeat} were an inanimate object, what would they be and why?",
  "What is the most trivial thing {hotSeat} has a strong opinion about?",
  "If {hotSeat} could be any mythical creature, what would they be and why?",
  "What is {hotSeatPossessive} biggest non-academic, non-work-related accomplishment?",
  "What is {hotSeatPossessive} biggest academic or work-related accomplishment?",
  "What is something {hotSeat} has done, felt, or seen that they wish they could experience again for the first time?",
  "If {hotSeat} could choose when and how they die, at what age would they choose and how would they want to go?",
  "What has been the happiest moment of {hotSeatPossessive} life so far?",
  "What would {hotSeat} do for $100 that no one else in the room would do for $1000?",
  "If {hotSeat} could go back in time and give their younger self one piece of advice, what would it be?",
  "What’s a phrase {hotSeat} says way too often?",
  "If {hotSeat} could instantly master any silly skill, what would it be?",
  "How does {hotSeat} usually handle stress?",
  "Who would {hotSeat} call if they needed advice?",
  "What nickname does {hotSeat} think would fit {randomPlayer} perfectly?",
  "If {hotSeat} had to give a TED Talk on a completely random topic, what would it be?",
  "If {hotSeat} had to choose one memory to keep while losing all others, which would they hold onto?",
  "What is the most normal thing that instantly overwhelms {hotSeat}?",
  "What is one thing {hotSeat} absolutely should not be trusted with?",
  "What is something {hotSeat} thinks they could beat {randomPlayer} at with absolutely zero practice?",
  "What is something {hotSeat} always plans to do \"tomorrow\" but never actually does?",
  "What is the most unnecessary thing {hotSeat} has strong opinions about?",
  "Hot seat is old and on their deathbed. With their last breath, they deliver their last words. What do they say and who do they say it to?",
  "What was the scariest moment of {hotSeatPossessive} life so far?",
  "What is the greatest physical pain {hotSeat} has ever felt?",
  "What is {hotSeat} most likely to be arrested for (in a harmless, comedic scenario)?",
  "What historical event would {hotSeat} have most liked to experience firsthand?",
  "What would {hotSeat} like to accomplish before 2026 is over?",
  "What is {hotSeatPossessive} favorite movie?",
  "What expensive thing does {hotSeat} believe is absolutely worth the money?",
  "What historical figure would {hotSeat} most like to sit and have a conversation with over tea?",
  "If {hotSeat} could live in any fictional world, where would they choose to live?",
  "What is {hotSeatPossessive} favorite memory with {randomPlayer}?",
  "What does {hotSeat} want written on their headstone?",
  "What is something {hotSeat} would jokingly say they'd \"sell a kidney\" for?",
  "What is something completely ordinary that {hotSeat} finds unexpectedly appealing or interesting?",
  "If a documentary about {hotSeatPossessive} life came out today, what would it be titled?",
  "What does {hotSeat} know more about than anyone else in the room?",
  "What would {hotSeatPossessive} porn star name be?",
  "What is the biggest change that will happen to {hotSeat} in the next five years?",
  "In a zombie apocalypse, what would {hotSeatPossessive} winning survival strategy be?",
  "What is the most bizarre thing {hotSeat} has ever witnessed someone else do?",
];

export function getShuffledQuestions(): string[] {
  const clone = [...QUESTION_BANK];
  for (let i = clone.length - 1; i > 0; i -= 1) {
    const j = Math.floor(Math.random() * (i + 1));
    const temp = clone[i]!;
    clone[i] = clone[j]!;
    clone[j] = temp;
  }
  return clone;
}
